type PropsProperty = {
  type: string;
  name: string;
};

export const filterPropertyItems: PropsProperty[] = [
  { type: 'apartment', name: 'Apartment' },
  { type: 'house', name: 'House' },
  { type: 'commercial', name: 'Commercial' },
  { type: 'land', name: 'Land' },
  { type: 'other', name: 'Other' },
];

export const filterBedroomsItems = {
  counter: [1, 2, 3, 4, 5],
  types: ['Studio'],
};

export const filterDistrictItems = [
  { name: 'All cities', id: 1 },
  {
    name: 'Limassol',
    id: 2,
    areas: [
      'Anglikos Stratos Akrotiriou',
      'Agios Athanasios',
      'Agios Amvrosios Lemesou',
      'Agios Georgios Lemesou',
      'Agios Dimitrios',
      'Agios Theodoros Lemesou',
      'Agios Therapon',
      'Agios Thomas',
      'Agios Ioannis Lemesou',
      'Agios Konstantinos',
      'Agios Mamas',
      'Agios Pavlos',
      'Agios Tychon Touristiki Periochi',
      'Agios Tychon',
      'Agridia',
      'Agros',
      'Athrakos',
      'Akapnou',
      'Akrounta',
      'Akrotiri',
      'Alassa',
      'Alektora',
      'Anogyra',
      'Apesia',
      'Arakapas',
      'Armenochori',
      'Arsos Lemesou',
      'Asgata',
      'Asomatos Lemesou',
      'Avdimou',
    ],
  },
  {
    name: 'Larnaca',
    id: 3,
    areas: [
      'Avdellero',
      'Anglikos Stratos Dekeleias',
      'Anglisides',
      'Agia Anna',
      'Agioi Vavatsinias',
      'Agios Theodoros Larnakas',
      'Athienou',
      'Alaminos',
      'Alethriko',
      'Anafotida',
      'Aplanta',
      'Aradippou',
      'Arsos Larnakas',
      'Vavatsinia',
      'Vavla',
      'Vasiliko',
      'Voroklini Touristiki Periochi',
      'Voroklini',
      'Dekeleia',
      'Delikipos',
      'Drapeia',
      'Dromolaxia',
      'Zygi',
      'Kalavasos',
      'Kalo Chorio Larnakas',
      'Kato Drys',
      'Kato Lefkara',
      'Kellia',
      'Kivisili',
      'Kiti',
    ],
  },
  {
    name: 'Nicosia',
    id: 4,
    areas: [
      'Anglikos Stratos Lefkosias',
      'Angolemi',
      'Agia Varvara Lefkosias',
      'Agia Eirini Lefkosias',
      'Agia Marina Xyliatou',
      'Agia Marina Skyllouras',
      'Agia',
      'Agio Georgoudi',
      'Agioi Iliofotoi',
      'Agioi Trimithias',
      'Agios Vasileios',
      'Agios Georgios Kafkallou',
      'Agios Georgios Soleas',
      'Agios Dometios',
      'Agios Epifanios Oreinis',
      'Agios Epifanios Soleas',
      'Agios Theodoros Soleas',
      'Agios Theodoros Tillirias',
      'Agios Ioannis Malountas',
      'Agios Ioannis Selemani',
      'Agios Nikolaos Lefkas',
      'Agios Nikolaos Stegis',
      'Agios Sozomenos',
      'Aglantzia',
      'Agrokipia',
      'Agroladou',
      'Akaki',
      'Alampra',
      'Alevga',
      'Alithinou',
    ],
  },
  {
    name: 'Paphos',
    id: 5,
    areas: [
      'Agia Varvara Pafou',
      'Agia Marina Kelokedaron',
      'Agia Marina Chrysochous',
      'Agia Marinouda',
      'Agios Georgios Pafou',
      'Agios Dimitrianos',
      'Agios Isidoros',
      'Agios Ioannis Pafou',
      'Agios Merkourios',
      'Agios Nikolaos Pafou',
      'Agios Fotios',
      'Akoursos',
      'Amargeti',
      'Ampelitis',
      'Anadiou',
      'Anarita',
      'Androlikou',
      'Axylou',
      'Argaka',
      'Arminou',
      'Armou',
      'Asprogia',
      'Acheleia',
      'Vretsia',
      'Galataria',
      'Geroskipou',
      'Giolou',
      'Goudi',
      'Dasikos Stathmos Agias',
      'Dasikos Stathmos Stavrou tis Psokas',
    ],
  },
  {
    name: 'Famagusta',
    id: 6,
    areas: [
      'Achna',
      'Agia',
      'Avgorou',
      'Ayia',
      'Deryneia',
      'Elias',
      'Frenaros',
      'Greko',
      'NapaAyia',
      'Kapparis',
      'Kokkinogremos',
      'Konnos',
      'Liopetri',
      'Paralimni',
      'Pernera',
      'Profitis',
      'Protaras',
      'Sotira',
      'Triada',
      'TheklaCape',
      'Vrysoulles',
    ],
  },
];

export const filterNavItems = [{ point: 'Rent' }, { point: 'Buy' }];
